<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-label_Verification Code</name>
   <tag></tag>
   <elementGuidId>7aea3d18-25bf-48ba-a25a-7d7f97beb87f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='mat-mdc-form-field-label-2']/mat-label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.ng-tns-c1205077789-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>0f25f7dc-70b9-4de2-8c51-c2db4a8f2e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1205077789-2</value>
      <webElementGuid>d51a7ec4-e3e0-45b4-9d12-286b6d4e56e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verification Code</value>
      <webElementGuid>e5c57085-19c7-455f-81bf-ab56a3976491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-form-field-label-2&quot;)/mat-label[@class=&quot;ng-tns-c1205077789-2&quot;]</value>
      <webElementGuid>63bab4e9-a49b-4200-8fae-f0b575cad508</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mat-mdc-form-field-label-2']/mat-label</value>
      <webElementGuid>50b8405a-59ac-4d80-a667-2829648caf29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check your Email'])[1]/following::mat-label[1]</value>
      <webElementGuid>05306db1-ce74-47b9-9c89-ceb77e2215e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[1]/following::mat-label[1]</value>
      <webElementGuid>f06f4143-0284-4b61-ba0c-11603fa1cd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>ef9c8b25-be45-46cb-b608-0e0c43563220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verification Code']/parent::*</value>
      <webElementGuid>ef9e5579-57ee-463a-931b-8068249f8bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-label</value>
      <webElementGuid>a48ba26b-8060-4e42-a3be-8865da6de8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Verification Code' or . = 'Verification Code')]</value>
      <webElementGuid>f37ef371-a1ff-4c91-8fb4-ec4e15e090d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
