<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nuevo Director</name>
   <tag></tag>
   <elementGuidId>001dc949-5b2b-49c0-bd03-59de256e0e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b7d66254-a301-4ad6-8578-2a9ddf9f644e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>67280786-b9dc-4642-8a36-439fe1dc9a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openMenuItem('menu_admin_item_4');</value>
      <webElementGuid>922cd62e-0cd9-4369-8527-ed7072246187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>item-href</name>
      <type>Main</type>
      <value>menu_admin_form_php.php?sc_item_menu=item_4&amp;sc_apl_menu=newDierector&amp;sc_apl_link=%2Fscriptcase9%2Fapp%2F&amp;sc_usa_grupo=S</value>
      <webElementGuid>5d56ddec-cc74-4bd0-8718-4b27de8273da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_4</value>
      <webElementGuid>acd78f4d-6199-4a4d-9aa4-0ef4ada301b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>item-target</name>
      <type>Main</type>
      <value>menu_admin_iframe</value>
      <webElementGuid>c3888c76-15fd-410f-a7f7-04a15080219b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu__link </value>
      <webElementGuid>1bce978a-8f3a-4174-91a1-fa4557914ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nuevo Director</value>
      <webElementGuid>9d67046f-0ce4-4bd5-baed-a49594adbce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_4&quot;)</value>
      <webElementGuid>98f21d94-3e87-4108-b074-5328841cf7d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='item_4']</value>
      <webElementGuid>1fe950ab-9739-41e0-ae57-30faf5753e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='css3menu1']/li[3]/ul/li/a</value>
      <webElementGuid>0564413e-5ff8-4076-a30d-ef84f78eec12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nuevo Director')]</value>
      <webElementGuid>e816e8c3-815b-4208-a304-2f6fdac4f401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/following::a[1]</value>
      <webElementGuid>99d921f3-60a7-43a8-98e2-8421a9d8b8a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva empresa'])[1]/following::a[2]</value>
      <webElementGuid>477e2674-de3e-4e1c-92ab-858439d52eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar pestaña'])[1]/preceding::a[1]</value>
      <webElementGuid>2aa3dddf-c0a2-4276-ae02-e48102037f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerrar todo'])[1]/preceding::a[1]</value>
      <webElementGuid>10bd46f9-25ae-4d91-b594-c23c64e55ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nuevo Director']/parent::*</value>
      <webElementGuid>de73607e-73c2-4982-b2c8-23707303b1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[5]</value>
      <webElementGuid>da73f322-c49c-4414-be9d-f32a83eb2f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/a</value>
      <webElementGuid>49d7a1be-4b5b-476a-b3ae-f8c6ff125e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:' and @id = 'item_4' and (text() = 'Nuevo Director' or . = 'Nuevo Director')]</value>
      <webElementGuid>7ef79bfd-a5bc-4670-9f9a-9a89d1487d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
