<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nueva empresa</name>
   <tag></tag>
   <elementGuidId>c4efdf14-75c2-4e0e-8f9b-14494027e554</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='item_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3567b269-3386-456a-9b56-48b49c9c2c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>6292d3c0-7921-458d-96d2-d1466f5d8154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openMenuItem('menu_admin_item_3');</value>
      <webElementGuid>2e4060ea-3a0e-4ce6-9cf9-a759d1478813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>item-href</name>
      <type>Main</type>
      <value>menu_admin_form_php.php?sc_item_menu=item_3&amp;sc_apl_menu=newCompany&amp;sc_apl_link=%2Fscriptcase9%2Fapp%2F&amp;sc_usa_grupo=S</value>
      <webElementGuid>5cfd125b-a60f-4d85-81db-cfeac42663a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>item_3</value>
      <webElementGuid>89ceb26e-7565-4951-aa30-eb9ec163afa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>item-target</name>
      <type>Main</type>
      <value>menu_admin_iframe</value>
      <webElementGuid>81840d28-4285-49d5-a5dd-b07916ec974f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu__link </value>
      <webElementGuid>c8c44510-ddbf-4f2c-8eb2-6c2c0249ed9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nueva empresa</value>
      <webElementGuid>dca882b4-de74-43ca-a851-a2181a8e0817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item_3&quot;)</value>
      <webElementGuid>fcd7636e-3d9b-4bd0-9a1c-37aefddc30ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='item_3']</value>
      <webElementGuid>167f6878-3e9b-4be7-8307-dcdcf7de1eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='css3menu1']/li[2]/ul/li/a</value>
      <webElementGuid>f4be4e0c-53f2-4041-85da-0c8232d8365e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nueva empresa')]</value>
      <webElementGuid>13f5235b-3423-4d0c-8e01-4b473482d198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empresas'])[1]/following::a[1]</value>
      <webElementGuid>e0abe6b8-2c93-4e19-bba6-3088529f4331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OZARU ONE'])[1]/following::a[2]</value>
      <webElementGuid>5db4f727-3970-4882-858d-361d7d104e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/preceding::a[1]</value>
      <webElementGuid>e2ac75a2-9a0b-4a25-819a-e523c6cbad8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo Director'])[1]/preceding::a[2]</value>
      <webElementGuid>b26b836a-54cf-494e-9868-0c358eeefd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nueva empresa']/parent::*</value>
      <webElementGuid>fe8f7e5f-cf24-4781-8e43-cef96fd48dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[3]</value>
      <webElementGuid>ca4acc51-2305-4af3-8c5d-92d20ac1e95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/a</value>
      <webElementGuid>74de3cca-ead1-49ed-bde1-eee49c534b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:' and @id = 'item_3' and (text() = 'Nueva empresa' or . = 'Nueva empresa')]</value>
      <webElementGuid>9c1c93ba-2d43-4037-9111-dd94ba870c0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
