<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ozaru One</name>
   <tag></tag>
   <elementGuidId>af71324c-924c-4630-aa08-18598e023b55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._ak72._ak73._ak7p > div._ak8l > div._ak8o > div._ak8q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane-side']/div[2]/div/div/div/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d95c9d2d-b936-4083-9f07-8b52f7dddc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_ak8q</value>
      <webElementGuid>a6c38d06-4618-4831-a645-8018031ca485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ozaru One</value>
      <webElementGuid>c843688d-d72c-4765-a3e5-347cd62f1ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane-side&quot;)/div[2]/div[1]/div[@class=&quot;x1y332i5 x1n2onr6 x6ikm8r x10wlt62&quot;]/div[@class=&quot;x10l6tqk xh8yej3 x1g42fcv&quot;]/div[@class=&quot;x1n2onr6&quot;]/div[1]/div[@class=&quot;_ak72 _ak73 _ak7p&quot;]/div[@class=&quot;_ak8l&quot;]/div[@class=&quot;_ak8o&quot;]/div[@class=&quot;_ak8q&quot;]</value>
      <webElementGuid>49311f6d-8fe6-42c2-ac7b-b1e4bb34c710</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane-side']/div[2]/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>e66883e1-6de9-43a3-ad01-59a941709768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Archivados'])[1]/following::div[17]</value>
      <webElementGuid>9880c75a-8f37-4d87-8439-4bec900507de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupos'])[1]/following::div[25]</value>
      <webElementGuid>4dc39782-9b90-4967-9006-e2de7bed46f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ayer'])[1]/preceding::div[2]</value>
      <webElementGuid>d371b8dc-596f-41ca-ad15-48bcc52e4133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>79f5f698-d1f2-4bff-8f7d-634d0146e1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ozaru One' or . = 'Ozaru One')]</value>
      <webElementGuid>f13c08e5-bb1b-4d53-b392-8802d96bf7c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
