<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ChatbotButton</name>
   <tag></tag>
   <elementGuidId>aacf46d0-499e-46e6-a490-3e93828272fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flowise-chatbot//button[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
