<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>flowise-chatbot-zaruOne-a03</name>
   <tag></tag>
   <elementGuidId>216c238e-f1dc-4655-ba0c-a69821cc073a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//flowise-chatbot</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flowise-chatbot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>flowise-chatbot</value>
      <webElementGuid>09b609a5-a2ab-4c63-ab6d-04c6bd617656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/flowise-chatbot[1]</value>
      <webElementGuid>1281165a-ca42-4478-b634-69d6367dd967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//flowise-chatbot</value>
      <webElementGuid>e56a76d4-c40c-4322-bf8e-41ff6b78314b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
