<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Supervisors_mat-icon notranslate icon material-icons mat-ligature-font mat-icon-no-color</name>
   <tag></tag>
   <elementGuidId>722cd766-23a3-4266-adb2-0b2153e9345a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//mat-icon[contains(@role,'img')])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>183362ea-e08b-4bbb-ba56-03436faf8357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>440d0504-dfb9-4fbe-b508-0bb69ae131d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>dd6807be-3f51-49f0-a7f3-cd18d897fd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>562b5c49-e1d4-4073-a4f8-a8624dfa5bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a2d6aba4-1dee-46d9-a16a-4d378fb16cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>a2ed6acb-4551-4d4e-9332-920b9fa78eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>cec55d53-9514-49f8-8527-0807d6756efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-pages[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;root-container&quot;]/div[@class=&quot;dashboard-container&quot;]/app-knowledge-manager[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;dashboard&quot;]/div[@class=&quot;cards-container&quot;]/div[@class=&quot;card-sub-container&quot;]/div[@class=&quot;card-standard&quot;]/div[@class=&quot;cards&quot;]/mat-card[@class=&quot;mat-mdc-card mdc-card card-standard card-brain card-grid ng-star-inserted&quot;]/div[@class=&quot;card-brain-header&quot;]/div[@class=&quot;menu-container more&quot;]/mat-icon[@class=&quot;mat-icon notranslate icon material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>1ec46b3c-cf61-4817-aa38-8bb71f48eb2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card[3]/div/div/mat-icon</value>
      <webElementGuid>dd4d3d19-a9f0-4b94-a59f-b48507327565</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
