<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-label_Description</name>
   <tag></tag>
   <elementGuidId>14f20e00-1f53-4ad4-86ee-e2dba1f8240b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[contains(@id,'description')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.ng-tns-c1205077789-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>143d91a8-9498-42aa-968c-d1042cd2fe99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1205077789-7</value>
      <webElementGuid>5a34514a-bd2e-4e8c-8cfb-82648cce52bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>088ede8e-7a70-469e-9105-1f96fa79bea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-form-field-label-8&quot;)/mat-label[@class=&quot;ng-tns-c1205077789-7&quot;]</value>
      <webElementGuid>4f3ccbef-b429-4b09-aaea-9409147d0357</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mat-mdc-form-field-label-8']/mat-label</value>
      <webElementGuid>e441142f-25b4-4e58-a8b2-ce91c2c42086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Name is required.'])[1]/following::mat-label[1]</value>
      <webElementGuid>b6b348c9-0402-43e6-8a7b-051b3edb9900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Name'])[1]/following::mat-label[1]</value>
      <webElementGuid>4e13dcdf-83ec-4446-b987-c13101090ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Description']/parent::*</value>
      <webElementGuid>4a85b689-3bc1-413f-8acb-df2147b593aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div/div/div/div[2]/label/mat-label</value>
      <webElementGuid>dd35b896-eaaf-4890-b06a-5201c962db3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Description' or . = 'Description')]</value>
      <webElementGuid>42790b8b-65f5-40d0-96f6-911e383f78e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
