<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Supervisors_mat-icon notranslate icon material-icons mat-ligature-font mat-icon-no-color</name>
   <tag></tag>
   <elementGuidId>722cd766-23a3-4266-adb2-0b2153e9345a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-card[3]/div/div/mat-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>5e877df2-7a65-4d0b-9dac-6f18ffa8c7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28ea702c-254d-4015-b7ef-152213fb749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>e87977ce-34f9-438a-8474-0ebdf7341000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate icon material-icons mat-ligature-font mat-icon-no-color</value>
      <webElementGuid>d575d7ae-dc31-4572-8415-85c5a43c9b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6e01894-7d2a-489a-b362-da99201e9449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>6025b978-8919-4554-8390-7e912c4309fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>more_vert</value>
      <webElementGuid>17727379-282f-4ab1-9122-9007ff8fc9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-pages[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;root-container&quot;]/div[@class=&quot;dashboard-container&quot;]/app-knowledge-manager[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;dashboard&quot;]/div[@class=&quot;cards-container&quot;]/div[@class=&quot;card-sub-container&quot;]/div[@class=&quot;card-standard&quot;]/div[@class=&quot;cards&quot;]/mat-card[@class=&quot;mat-mdc-card mdc-card card-standard card-brain card-grid ng-star-inserted&quot;]/div[@class=&quot;card-brain-header&quot;]/div[@class=&quot;menu-container more&quot;]/mat-icon[@class=&quot;mat-icon notranslate icon material-icons mat-ligature-font mat-icon-no-color&quot;]</value>
      <webElementGuid>0db78fba-0339-4244-beb3-a558f117d6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card[3]/div/div/mat-icon</value>
      <webElementGuid>95b3a44b-e1bf-4bc9-81b3-ebad73a2cf48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
