<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-label_Role Name</name>
   <tag></tag>
   <elementGuidId>63ffc0b5-38a1-449c-90d7-5894afc7af76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'role_name')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.ng-tns-c1205077789-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>4930d45b-994f-4128-a953-9864febbcb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1205077789-6</value>
      <webElementGuid>e865d249-c3f6-49ab-953e-4314ca38ac05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Role Name</value>
      <webElementGuid>7f103deb-5eb8-4e54-a8de-978eaa5dc7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-form-field-label-6&quot;)/mat-label[@class=&quot;ng-tns-c1205077789-6&quot;]</value>
      <webElementGuid>2510fe5a-32f7-4d13-ab21-9625726b8ba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mat-mdc-form-field-label-6']/mat-label</value>
      <webElementGuid>74e3934e-67f2-4a26-9617-fc1416cb66b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role Details'])[1]/following::mat-label[1]</value>
      <webElementGuid>d5bc6bea-1b4a-4caa-b939-216b5fba1f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch is required.'])[1]/following::mat-label[1]</value>
      <webElementGuid>f0cc86c0-30cc-47d8-b4e7-5bdb8d5b1477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>8e2bdc24-c173-4d7a-b78d-a8a58bff7720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Role Name']/parent::*</value>
      <webElementGuid>150c8637-9561-4eb6-980f-f6234d860427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-form-field/div/div/div/div[2]/label/mat-label</value>
      <webElementGuid>bb70a775-2e6c-4645-8c2a-5e1b03029b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Role Name' or . = 'Role Name')]</value>
      <webElementGuid>57417c38-3248-4326-a595-100c52df31c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
