<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-label_Time Zone</name>
   <tag></tag>
   <elementGuidId>0d65e107-afa4-4a4f-b48b-295611e0e7c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='time_zone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-label.ng-tns-c1205077789-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-label</value>
      <webElementGuid>bcde0c0a-6481-4a88-94e5-1ca5fc790270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c1205077789-8</value>
      <webElementGuid>9204fce5-777d-4b03-9bd1-74ea121aceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time Zone</value>
      <webElementGuid>b13f22a9-2e95-457d-a1d1-b7c991880462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-form-field-label-8&quot;)/mat-label[@class=&quot;ng-tns-c1205077789-8&quot;]</value>
      <webElementGuid>89ad97a5-9a14-492b-9783-4bbcc0f978d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='mat-mdc-form-field-label-8']/mat-label</value>
      <webElementGuid>c407726e-33c7-43ce-ad74-762d4731812d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Zone'])[1]/following::mat-label[1]</value>
      <webElementGuid>c60fdbb9-424c-418a-b7ce-00b7f79134ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational Role is required.'])[1]/following::mat-label[1]</value>
      <webElementGuid>052cd75b-5334-4544-9eb4-ae7716dd0ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User details'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>192392ca-1b73-4746-b974-407d4f76107a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Full name'])[1]/preceding::mat-label[1]</value>
      <webElementGuid>d4eb9398-b103-4a2a-9705-6f25e57fecf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-form-field/div/div/div/div[2]/label/mat-label</value>
      <webElementGuid>ce77340b-fffc-4ebe-98fd-0387f713972e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-label[(text() = 'Time Zone' or . = 'Time Zone')]</value>
      <webElementGuid>bf689f81-80d1-4cb4-bbe6-adc1b340cd66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
