<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Schedule Day_ng-tns-c3393473648-10 OP</name>
   <tag></tag>
   <elementGuidId>0fb47703-6f7c-47ff-8754-517e01798fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path.ng-tns-c3393473648-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>14267991-5246-4d0a-b6ab-f4a2b71ee0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M7 10l5 5 5-5z</value>
      <webElementGuid>0280dfea-8db5-47ba-a996-c2b5c3d62f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c3393473648-10</value>
      <webElementGuid>5d66509c-fce2-4ee0-976a-9d8f8ff6fc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scheduleDay&quot;)/div[@class=&quot;mat-mdc-select-trigger ng-tns-c3393473648-10&quot;]/div[@class=&quot;mat-mdc-select-arrow-wrapper ng-tns-c3393473648-10&quot;]/div[@class=&quot;mat-mdc-select-arrow ng-tns-c3393473648-10&quot;]/svg[@class=&quot;ng-tns-c3393473648-10&quot;]/path[@class=&quot;ng-tns-c3393473648-10&quot;]</value>
      <webElementGuid>86437182-5692-4468-973c-552e2f375f66</webElementGuid>
   </webElementProperties>
</WebElementEntity>
