<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_testting</name>
   <tag></tag>
   <elementGuidId>b8fdbc76-1d27-4f09-95e1-481a9108193a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-5']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mdc-list-item__primary-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75313e07-4f1d-4285-a906-a2ab3c58e30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item__primary-text</value>
      <webElementGuid>2da00f31-ddc5-4999-9ded-7023ab750f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> testting </value>
      <webElementGuid>a6eab416-a31e-4e0d-a25f-5dfd4a8f908b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-5&quot;)/span[@class=&quot;mdc-list-item__primary-text&quot;]</value>
      <webElementGuid>f70a5eaa-35bc-4f23-831a-3d7e22a6c61a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-5']/span</value>
      <webElementGuid>984c734e-0613-4293-aaa7-0039fb3f4d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[1]</value>
      <webElementGuid>8cbb111b-a0c6-4632-b3e6-b45e39c4cd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testting']/parent::*</value>
      <webElementGuid>07323771-5082-4477-89a9-61f751060005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>1f27dc97-e4a8-4406-9c96-4a459e2e5347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' testting ' or . = ' testting ')]</value>
      <webElementGuid>81a6f154-93ec-4dfa-94ac-50b8231de36b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
