<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_prueba</name>
   <tag></tag>
   <elementGuidId>01d0343c-8b94-414f-a6f2-443d4072be87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-231']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-231 > span.mdc-list-item__primary-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9935abe4-9dcd-45ef-b38f-07af5dbd38e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdc-list-item__primary-text</value>
      <webElementGuid>6f95606d-886e-46ec-8b99-8ff7cec41cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> prueba </value>
      <webElementGuid>17089d95-a664-40e9-9042-63cd4ecf8c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-231&quot;)/span[@class=&quot;mdc-list-item__primary-text&quot;]</value>
      <webElementGuid>b77d8a30-8451-4781-8c4b-f0a3a9ab026a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-231']/span</value>
      <webElementGuid>37685434-9d1e-4493-abd2-ecc1d279299c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Operational Role'])[2]/following::span[1]</value>
      <webElementGuid>6590d71f-ff18-4c8b-a93d-845155701b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::span[2]</value>
      <webElementGuid>b3838e01-0e67-4ca9-b239-9223989aff7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testting'])[1]/preceding::span[1]</value>
      <webElementGuid>a80890d9-b5d6-4146-8d85-855540f25a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='prueba']/parent::*</value>
      <webElementGuid>48bc7839-cf92-4d46-90c9-ba573cf2afaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[2]/span</value>
      <webElementGuid>da0eb397-895a-44a6-8b60-f7039a02de63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' prueba ' or . = ' prueba ')]</value>
      <webElementGuid>749bc1ff-75e8-484c-84c8-931b4468d2de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
